apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-anomaly-service
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-anomaly-service
  template:
    metadata:
      labels:
        app: ai-anomaly-service
    spec:
      containers:
      - name: ai-anomaly-service
        image: ghcr.io/roshaan1103/ai-anomaly-service:5e7bd72eac5b50c27aa5ebe30a326cd74c333ed7
        ports:
        - containerPort: 8000
