apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-prometheus-kube-prometheus-alertmanager
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: "default"
      routes:
      - match:
          severity: warning
        receiver: "ai-webhook"

    receivers:
    - name: "default"
    # you can keep empty OR later add Slack/Email

    - name: "ai-webhook"
      webhook_configs:
      - url: "http://ai-anomaly-service.monitoring.svc.cluster.local:8000/alert"
        send_resolved: true
