apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aiops-app
  name: aiops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aiops-app
  template:
    metadata:
      labels:
        app: aiops-app
    spec:
      containers:
      - name: aiops-app
        image: ghcr.io/roshaan1103/k8sagro-helm-app:cd8a0c789c942d73d4e2ee7770b7e5780476ba82
        ports:
        - containerPort: 8000
