apiVersion: v1
kind: Service
metadata:
  labels:
    app: aiops-app
  name: aiops-service
spec:
  type: NodePort
  selector:
    app: aiops-app
  ports:
  - name: http            # <--- add this
    nodePort: 30007
    port: 80
    protocol: TCP
    targetPort: 8000
